<?php

namespace src\Delivery\Http\Product\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class GetProductRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'id' => 'required|uuid'
        ];
    }

    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation()
    {
        $this->merge(['id' => $this['id']]);
    }

    protected function failedValidation(Validator $validator)
    {
        dd($validator);
//        throw new HttpResponseException(
//            failValidate($validator)
//        );
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
