FROM docker.arvancloud.ir/golang:1.24-alpine3.21

WORKDIR /app

ENV GOPROXY=https://goproxy.io,direct
ENV TZ=Asia/Tehran
ARG ENV_FILE=.env
ENV ENV_FILE=${ENV_FILE}

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY .air.toml .
COPY $ENV_FILE .env

EXPOSE 8000

CMD ["air", "-c", ".air.toml"]