services:
  gitlab:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: git.developeryar-local.ir
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.developeryar-local.ir'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - laravel_network
  user-service:
    build: ./users-service
    container_name: users-service
    restart: unless-stopped
    volumes:
      - ./users-service:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  product-service:
    build: ./products-service
    container_name: products-service
    restart: unless-stopped
    volumes:
      - ./products-service:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql

  order-service:
    build: ./orders-service
    deploy:
      replicas: 3
    restart: unless-stopped
    volumes:
      - ./orders-service:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: three_services
      MYSQL_PASSWORD:
    networks:
      - laravel_network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/opt/mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/developeryar-local.ir:/etc/nginx/ssl:ro
    networks:
      - laravel_network
    depends_on:
      - gitlab
      - user-service
      - product-service
      - order-service

networks:
  laravel_network:
    driver: bridge
    attachable: true
    name: laravel_network
    external: false
volumes:
  mysql_data:
    driver: local
  gitlab_config:
  gitlab_logs:
  gitlab_data: