version: '3.8'

services:
  gitlab:
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2048M
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: git.developeryar.ir
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.developeryar.ir'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        puma['worker_processes'] = 0
        sidekiq['concurrency'] = 10
        prometheus_monitoring['enable'] = false
        nginx['listen_port'] = 80
    ports:
      - "2222:22"
      - "8181:8181"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/-/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - laravel_network
    depends_on:
      - gitlab

networks:
  laravel_network:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
