services:
  gitlab:
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2560M
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: git.developeryar.ir
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.developeryar.ir'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        puma['worker_processes'] = 1
        sidekiq['max_concurrency'] = 5
        postgresql['shared_buffers'] = "256MB"
        postgresql['max_worker_processes'] = 2
        redis['max_memory'] = "128MB"
        prometheus_monitoring['enable'] = false
        grafana['enable'] = false
        alertmanager['enable'] = false
    ports:
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/-/health || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 10m

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - laravel_network
    depends_on:
      - gitlab

networks:
  laravel_network:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
